# cert-manager is installed using kubectl -f https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml
# Certificate we are creating using cert-manager is valid throughout the Cluster
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: xxxxxxxxxxxx@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx